namespace CRM.Enterprise.Api.Contracts.Decisions;

public record DecisionStepItem(
    int StepOrder,
    string StepType,
    string Status,
    Guid? AssigneeUserId,
    string? AssigneeName,
    string? ApproverRole,
    DateTime? DueAtUtc,
    DateTime? CompletedAtUtc);

public record DecisionInboxItem(
    Guid Id,
    string DecisionType,
    string WorkflowType,
    string EntityType,
    Guid EntityId,
    string EntityName,
    string? ParentEntityName,
    string Status,
    string Purpose,
    string Priority,
    string RiskLevel,
    string SlaStatus,
    DateTime? SlaDueAtUtc,
    bool IsEscalated,
    double RequestedAgeHours,
    string PolicyReason,
    string BusinessImpactLabel,
    decimal Amount,
    string Currency,
    Guid? RequestedByUserId,
    string? RequestedByName,
    Guid? AssigneeUserId,
    string? AssigneeName,
    DateTime RequestedOn,
    DateTime? DecisionOn,
    string? Notes,
    int CurrentStepOrder,
    int TotalSteps,
    string? StepRole,
    string? ChainStatus,
    IReadOnlyList<DecisionStepItem> Steps);
