/** Models for the Lead Import Wizard. */
export const LEAD_FIELD_OPTIONS = [
    { label: '— Skip this column —', value: '' },
    { label: 'First Name', value: 'firstName' },
    { label: 'Last Name', value: 'lastName' },
    { label: 'Full Name', value: 'name' },
    { label: 'Email', value: 'email' },
    { label: 'Phone', value: 'phone' },
    { label: 'Company', value: 'company' },
    { label: 'Job Title', value: 'jobTitle' },
    { label: 'Status', value: 'status' },
    { label: 'Source', value: 'source' },
    { label: 'Territory', value: 'territory' },
    { label: 'Score', value: 'score' },
    { label: 'Owner', value: 'owner' },
    { label: 'Buyer Type', value: 'buyerType' },
    { label: 'Budget Band', value: 'budgetBand' },
    { label: 'Preferred Area', value: 'preferredArea' },
    { label: 'Preferred Property Type', value: 'preferredPropertyType' }
];
/** Auto-mapping from lowercase CSV header to field value. */
export const AUTO_MAP = {
    firstname: 'firstName',
    first_name: 'firstName',
    'first name': 'firstName',
    lastname: 'lastName',
    last_name: 'lastName',
    'last name': 'lastName',
    name: 'name',
    fullname: 'name',
    full_name: 'name',
    'full name': 'name',
    email: 'email',
    'e-mail': 'email',
    phone: 'phone',
    telephone: 'phone',
    mobile: 'phone',
    company: 'company',
    companyname: 'company',
    company_name: 'company',
    'company name': 'company',
    organization: 'company',
    jobtitle: 'jobTitle',
    job_title: 'jobTitle',
    'job title': 'jobTitle',
    title: 'jobTitle',
    status: 'status',
    source: 'source',
    lead_source: 'source',
    'lead source': 'source',
    territory: 'territory',
    region: 'territory',
    score: 'score',
    lead_score: 'score',
    'lead score': 'score',
    owner: 'owner',
    assigned_to: 'owner',
    'assigned to': 'owner'
};
