using System;

namespace CRM.Enterprise.Api.Contracts.Properties;

public record PropertyListItem(
    Guid Id,
    string? MlsNumber,
    string Address,
    string? City,
    string? Province,
    string? PostalCode,
    decimal? ListPrice,
    decimal? SalePrice,
    string Currency,
    DateTime? ListingDateUtc,
    DateTime? SoldDateUtc,
    string Status,
    string PropertyType,
    int? Bedrooms,
    int? Bathrooms,
    decimal? SquareFeet,
    decimal? LotSizeSqFt,
    int? YearBuilt,
    int? GarageSpaces,
    string? Description,
    string? Features,
    string? PhotoUrls,
    string? VirtualTourUrl,
    Guid OwnerId,
    string? OwnerName,
    Guid? AccountId,
    string? AccountName,
    Guid? PrimaryContactId,
    string? PrimaryContactName,
    Guid? OpportunityId,
    string? Neighborhood,
    DateTime CreatedAtUtc);
